### ISSUE TITLE
map scale problems

### ISSUE THREAD

**Issue by Kladek00** [HannaM-K/UnityGroupProject#23]
we have places on the map that are not scaled for character model.

![mapscale1](https://user-images.githubusercontent.com/57038395/70862589-95ce9a80-1f3e-11ea-980b-7bbf53e1c66f.jpg)
![mapscale2](https://user-images.githubusercontent.com/57038395/70862606-c0205800-1f3e-11ea-9ede-c102ae7e5669.jpg)
![mapscale3](https://user-images.githubusercontent.com/57038395/70862637-14c3d300-1f3f-11ea-98bc-362aa82189af.jpg)

**Comment by Adarat** [comment]
Click ctrl
